name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install components
      run: rustup component add rustfmt clippy
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Check build
      run: cargo check
    - name: Run tests
      run: cargo test --all-targets
